#!/bin/sh

test $# -lt 1 && exit 1

while read t; do

    # get path
    pth=$(echo "$t" | sed -E 's/[^\/]+$//g')

    # strip out path and extension
    fn=$(echo "$t" | sed -E 's/.+\///g' | sed -E 's/\.[^\/.]+$//g')
    
    if ls -d "$pth$fn/" > /dev/null 2>&1; then
        fp=$(find "$pth" -type d -regextype 'posix-egrep' -regex ".*$fn( \(COPY\))*$" | sort -r | head -1)
        mkdir "$fp (COPY)"
        mv "$t" "$fp (COPY)"
    else
        mkdir "$pth$fn (TEMP)"
        mv "$t" "$pth$fn (TEMP)"
        mv "$pth$fn (TEMP)" "$pth$fn"
    fi

done << EOF
    $(find "$1" -maxdepth 1 -type f)
EOF

exit $?
