#!/bin/sh

#strip trailing slash in path argument
pth=$(echo $1 | sed -E 's/\/$//g')

while read t; do

    # strip out path and extension
    fn=$(echo "$t" | sed -E 's/^.+\/([^\/]+)\.[^.\/]+$/\1/g')

    mkdir "$pth/$fn" 2> /dev/null
    
    # in case of naming conflict and the folder could not be created
    if test $? -ne 0; then

        hits=$(find "$pth" -type d -name "${fn}*")
        fn=$(echo "$hits" | grep -E "${fn}( \(COPY\))*$" | sort -r | head -1)
        mkdir "$pth/$fn (COPY)"

    fi

    mv "$t" "$pth/$fn"

done << EOF
    $(find "$pth" -maxdepth 1 -type f)
EOF

exit 0
